// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZTTkqxAtnjfbZie2MZwWzUAsrnmIU7Y',
    appId: '1:469263852220:web:093d0c3542fd7ae119a6b9',
    messagingSenderId: '469263852220',
    projectId: 'full-stack-app-dev-26-6bf3c',
    authDomain: 'full-stack-app-dev-26-6bf3c.firebaseapp.com',
    storageBucket: 'full-stack-app-dev-26-6bf3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN1OvL-jn6zqzbtmTPmNeA3vv0xmotZ4s',
    appId: '1:469263852220:android:3f914c32f225187319a6b9',
    messagingSenderId: '469263852220',
    projectId: 'full-stack-app-dev-26-6bf3c',
    storageBucket: 'full-stack-app-dev-26-6bf3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUfjwWJvO0YEAzN4vdUOGlXIQv9ggZm5o',
    appId: '1:469263852220:ios:e7fd1b793e88b59a19a6b9',
    messagingSenderId: '469263852220',
    projectId: 'full-stack-app-dev-26-6bf3c',
    storageBucket: 'full-stack-app-dev-26-6bf3c.firebasestorage.app',
    iosBundleId: 'com.example.fluterFirebaseHomework',
  );
}
